# First test pipeline


trigger:
- master

pool:
  vmImage: Default

stages:

  - stage: stage1
    displayName: stage 1 started
    jobs:

      - job: job1
        displayName: job 1 started
        steps:

          - script: echo "Hello World"
